langugae: generic
sudo: required
services: 
    - docker

befor_install: 
    - docker build -t javad/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true javad/docker-react npm run test
